### ISSUE TITLE
mybinder.org link does not work anymore

### ISSUE THREAD

**Issue by lrq3000** [nipy/niwidgets#31]
Terrific widgets package you made, great job!

I tried the online interactive demo, but none of the notebooks work, probably the package is not updated there?

Also the link to mybinder is buggy in the documentation:
http://nipy.org/niwidgets/examples.html

**Comment by janfreyberg** [comment]
This should be fixed since commit 5f24a5004aefaf35ab73ef88993988b12f9b0501
